# -*- coding: utf-8 -*-
"""SafeScan_Step1_IITPatna.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tKcnrUxegKw12SkDUR9YYd-GFj16o3wN

# SafeScan - Step 1 (v2): IIT Patna Indian Grocery Dataset - Download, Crop, Categorize, OCR

This replaces the Freiburg-based Step 1. This notebook:
1. Downloads the Grocery_Items dataset (IIT Patna, via Roboflow) - 6,695 images, object detection format
2. Crops individual products out of each image using the bounding box annotations
3. Collapses the 4,400+ specific brand classes into ~20 broad food categories (keyword-based)
4. Runs OCR on every cropped product image
5. Saves everything in the same folder structure used by Step 2 (category -> images + JSON)

**Runtime setup:** Runtime -> Change runtime type -> GPU (T4)

## Cell 1 - Install packages
"""

!pip install roboflow easyocr -q

"""## Cell 2 - Download the dataset from Roboflow

Paste your Roboflow API key below (Settings -> API Keys on roboflow.com).
Check the "Dataset" tab on the project page for the correct version number - update
`VERSION_NUMBER` if it's not 1.

"""

from roboflow import Roboflow

ROBOFLOW_API_KEY = "NF0VRF6Z7nqBqFXUHEeG"
VERSION_NUMBER = 45   # check the "Dataset" tab on the project page and update if needed

rf = Roboflow(api_key=ROBOFLOW_API_KEY)
project = rf.workspace("iit-patna-qg1jh").project("grocery_items-7i2em")
version = project.version(VERSION_NUMBER)
dataset = version.download("coco")  # COCO format gives us images + bounding box annotations

print("Downloaded to:", dataset.location)

import os
print(os.listdir(dataset.location))

"""**STOP HERE.** Check the printed output. COCO format usually gives folders like
`train/`, `valid/`, `test/`, each containing images plus an `_annotations.coco.json` file.
If the folder names differ, update `SPLIT_FOLDERS` in Cell 4 below to match.

"""

train_path = os.path.join(dataset.location, "train")
print(os.listdir(train_path)[:10])  # should show image files + _annotations.coco.json

"""## Cell 3 - Define the category collapsing map (4,400+ classes -> ~20 broad food categories)

This uses keyword matching against each original class name. Classes that don't match any
food-related keyword (e.g. toothpaste, air freshener, detergent) are dropped, since they are
not relevant to nutrition/allergen analysis. You can edit these keyword lists any time to
improve the mapping.

"""

CATEGORY_KEYWORDS = {
    "TEA":            ["tea"],
    "MILK":           ["milk"],
    "BUTTER":         ["butter"],
    "CHEESE":         ["cheese"],
    "RICE":           ["rice"],
    "SUGAR":          ["sugar"],
    "SALT":           ["salt"],
    "SPICES":         ["spice", "masala", "chilli", "turmeric", "pepper", "cumin", "coriander", "powder"],
    "BISCUITS":       ["biscuit", "cookie"],
    "CHOCOLATE_CANDY":["chocolate", "candy", "choco", "sweet"],
    "CHIPS_SNACKS":   ["chips", "fryums", "snack", "namkeen", "bhujia", "popcorn"],
    "SAUCE_KETCHUP":  ["sauce", "ketchup", "chutney", "vinegar"],
    "OIL":            ["oil"],
    "CEREAL":         ["cereal", "cornflakes", "oats", "muesli"],
    "SOFTDRINK_JUICE":["juice", "softdrink", "cola", "soda", "drink", "fizz"],
    "PICKLE":         ["pickle", "achar"],
    "HONEY":          ["honey"],
    "NOODLES_PASTA":  ["noodle", "pasta", "maggi", "vermicelli"],
    "PULSES_DAL":     ["dal", "pulse", "lentil", "chana", "rajma"],
    "WATER":          ["water"],
    "ALMONDS_NUTS":   ["almond", "nut", "cashew", "pista"],
}

def map_to_broad_category(class_name):
    """Returns the broad category for a given original class name, or None if no match."""
    name_lower = class_name.lower()
    for broad_cat, keywords in CATEGORY_KEYWORDS.items():
        for kw in keywords:
            if kw in name_lower:
                return broad_cat
    return None

# quick test
test_names = ["Aashirvaad_ChilliPowder", "Almondo_Amul", "ToothPaste_Colgate", "Butter_Amul"]
for n in test_names:
    print(f"{n} -> {map_to_broad_category(n)}")

"""## Cell 4 - Crop products from each image using bounding boxes, sorted into broad categories"""

import json
from PIL import Image

SPLIT_FOLDERS = ["train", "valid", "test"]   # update based on Cell 2's printed output
CROPPED_OUTPUT_ROOT = "/content/iitpatna_cropped"

os.makedirs(CROPPED_OUTPUT_ROOT, exist_ok=True)

def crop_and_categorize(dataset_location, split_folders, output_root, max_per_class=None):
    category_counts = {}

    for split in split_folders:
        split_path = os.path.join(dataset_location, split)
        ann_path = os.path.join(split_path, "_annotations.coco.json")
        if not os.path.exists(ann_path):
            print(f"Skipping {split} - no annotations file found")
            continue

        with open(ann_path, 'r') as f:
            coco = json.load(f)

        # Build lookup: category_id -> original class name
        cat_id_to_name = {c['id']: c['name'] for c in coco['categories']}
        # Build lookup: image_id -> file_name
        img_id_to_file = {img['id']: img['file_name'] for img in coco['images']}

        print(f"\nProcessing split: {split} ({len(coco['annotations'])} annotations)")

        for ann in coco['annotations']:
            orig_class_name = cat_id_to_name.get(ann['category_id'], "")
            broad_cat = map_to_broad_category(orig_class_name)
            if broad_cat is None:
                continue  # not a food-relevant class, skip

            if max_per_class and category_counts.get(broad_cat, 0) >= max_per_class:
                continue

            img_file = img_id_to_file.get(ann['image_id'])
            if img_file is None:
                continue
            img_path = os.path.join(split_path, img_file)
            if not os.path.exists(img_path):
                continue

            try:
                img = Image.open(img_path).convert("RGB")
                x, y, w, h = ann['bbox']  # COCO format: [x_min, y_min, width, height]
                cropped = img.crop((x, y, x + w, y + h))

                cat_folder = os.path.join(output_root, broad_cat)
                os.makedirs(cat_folder, exist_ok=True)

                count = category_counts.get(broad_cat, 0)
                save_path = os.path.join(cat_folder, f"{broad_cat}_{count:04d}.jpg")
                cropped.save(save_path)

                category_counts[broad_cat] = count + 1
            except Exception as e:
                print(f"  Error cropping annotation {ann['id']}: {e}")

    return category_counts

# NOTE: set max_per_class=20 first for a quick pipeline test, then re-run with None for full data
category_counts = crop_and_categorize(dataset.location, SPLIT_FOLDERS, CROPPED_OUTPUT_ROOT, max_per_class=800)
print("\nFinal category counts:", category_counts)

"""**Note on the quick test run:** same idea as before - `max_per_class=20` lets you verify
cropping and categorization work correctly in a few minutes. Once confirmed, change it to
`max_per_class=None` and re-run Cell 4 for the full dataset.

## Cell 5 - Set up OCR reader
"""

import easyocr
reader = easyocr.Reader(['en'])
print("EasyOCR reader ready.")

"""## Cell 6 - Run OCR on the cropped, categorized images"""

OUTPUT_TEXT_ROOT = "/content/iitpatna_ocr_text"
os.makedirs(OUTPUT_TEXT_ROOT, exist_ok=True)

def run_ocr_on_dataset(images_root, output_root):
    categories = sorted(os.listdir(images_root))
    print(f"Found {len(categories)} categories: {categories}")

    for category in categories:
        cat_img_path = os.path.join(images_root, category)
        if not os.path.isdir(cat_img_path):
            continue

        cat_output_path = os.path.join(output_root, category)
        os.makedirs(cat_output_path, exist_ok=True)

        img_files = [f for f in os.listdir(cat_img_path) if f.lower().endswith('.jpg')]
        print(f"\nProcessing category: {category} ({len(img_files)} images)")

        for idx, img_file in enumerate(img_files):
            img_path = os.path.join(cat_img_path, img_file)
            try:
                results = reader.readtext(img_path)
                ocr_json = [{"description": text, "confidence": float(conf)}
                            for (bbox, text, conf) in results]
                json_filename = img_file.rsplit('.', 1)[0] + '.json'
                json_path = os.path.join(cat_output_path, json_filename)
                with open(json_path, 'w', encoding='utf-8') as f:
                    json.dump(ocr_json, f, ensure_ascii=False, indent=2)
            except Exception as e:
                print(f"  Error processing {img_file}: {e}")

            if (idx + 1) % 20 == 0:
                print(f"  Processed {idx + 1}/{len(img_files)} images...")

    print("\nOCR extraction complete!")

run_ocr_on_dataset(CROPPED_OUTPUT_ROOT, OUTPUT_TEXT_ROOT)

"""## Cell 7 - download everything"""

sample_category = os.listdir(OUTPUT_TEXT_ROOT)[0]
sample_folder = os.path.join(OUTPUT_TEXT_ROOT, sample_category)
sample_json = os.listdir(sample_folder)[0]
with open(os.path.join(sample_folder, sample_json), 'r') as f:
    print(json.load(f))

import os, json

categories = os.listdir(OUTPUT_TEXT_ROOT)
print(f"Checking {len(categories)} categories...\n")

for cat in categories[:8]:
    cat_folder = os.path.join(OUTPUT_TEXT_ROOT, cat)
    json_files = os.listdir(cat_folder)

    found_text = False
    for jf in json_files[:5]:
        with open(os.path.join(cat_folder, jf), 'r') as f:
            data = json.load(f)
        if len(data) > 0:
            print(f"[{cat}] {jf}: {[d['description'] for d in data]}")
            found_text = True
            break
    if not found_text:
        print(f"[{cat}] — no text found in first 5 samples checked")
    print()

# Zip and download both the cropped images and the OCR text - you'll need both for Step 2
!zip -rq iitpatna_cropped.zip /content/iitpatna_cropped
!zip -rq iitpatna_ocr_text.zip /content/iitpatna_ocr_text

from google.colab import files
files.download('iitpatna_cropped.zip')
files.download('iitpatna_ocr_text.zip')